# Docker compose for production deployment

version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: ["prefect", "server", "start"]
    env_file:
      - .env
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_URL=http://host:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=${DATABASE_URL}
      - PREFECT_API_DATABASE_MIGRATE_ON_START=True
    ports:
      - 4200:4200

  flows:
    build:
      context: .
      dockerfile: Dockerfile
      target: flows
    entrypoint: ["python", "/app/code/main.py"]
    env_file:
      - .env
    volumes:
      - ./code:/app/code
    restart: always
    depends_on:
      - server
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - PYTHONPATH=/app/code

volumes:
  prefect:
